# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-11 21:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akademisyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aka_bilgi', models.CharField(max_length=60, verbose_name='Akademisyen Ad-Soyad')),
            ],
            options={
                'verbose_name': 'Akademisyenler',
                'verbose_name_plural': 'Akademisyenler',
            },
        ),
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum_adi', models.CharField(choices=[('Bilgisayar Mühendisliği', 'Bilgisayar Mühendisliği'), ('Elektrik Elektronik Mühendisliği', 'Elektrik Elektronik Mühendisliği'), ('Harita Mühendisliği', 'Harita Mühendisliği'), ('İnşaat Mühendisliği', 'İnşaat Mühendisliği'), ('Jeofizik Mühendisliği', 'Jeofizik Mühendisliği'), ('Jeoloji Mühendisliği', 'Jeoloji Mühendisliği'), ('Maden Mühendisliği', 'Maden Mühendisliği'), ('Makine Mühendisliği', 'Makine Mühendisliği'), ('Metalurji ve Malzeme Mühendisliği', 'Metalurji ve Malzeme Mühendisliği'), ('Orman Mühendisliği', 'Orman Mühendisliği'), ('Orman Endüstri Mühendisliği', 'Orman Endüstri Mühendisliği')], default='Bilgisayar Mühendisliği', max_length=50, verbose_name='Bölüm Adı')),
            ],
            options={
                'verbose_name': 'Bölümler',
                'verbose_name_plural': 'Bölümler',
            },
        ),
        migrations.CreateModel(
            name='Cikti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cikti_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Çıktı Numarası')),
                ('cikti_tani', models.TextField(verbose_name='Çıktı Tanımı')),
                ('cikti_tarih', models.DateField(verbose_name='Çıktı Tarihi')),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudek.Bolum')),
            ],
            options={
                'verbose_name': 'Çıktılar',
                'verbose_name_plural': 'Çıktılar',
            },
        ),
        migrations.CreateModel(
            name='Cikti_Basari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basari_oran', models.FloatField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Çıktı Başarı Oranı')),
                ('cikti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudek.Cikti')),
            ],
            options={
                'verbose_name': 'Çıktı Başarı Oranı',
                'verbose_name_plural': 'Çıktı Başarı Oranı',
            },
        ),
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_kodu', models.CharField(max_length=15, verbose_name='Ders Kodu')),
                ('ders_adi', models.CharField(max_length=50, verbose_name='Ders Adı')),
                ('egit_yil', models.CharField(choices=[('2000 - 2001 ', ' 2000 - 2001'), ('2001 - 2002 ', ' 2001 - 2002'), ('2002 - 2003 ', ' 2002 - 2003'), ('2003 - 2004 ', ' 2003 - 2004'), ('2004 - 2005 ', ' 2004 - 2005'), ('2005 - 2006 ', ' 2005 - 2006'), ('2006 - 2007 ', ' 2006 - 2007'), ('2007 - 2008 ', ' 2007 - 2008'), ('2008 - 2009 ', ' 2008 - 2009'), ('2009 - 2010 ', ' 2009 - 2010'), ('2010 - 2011 ', ' 2010 - 2011'), ('2011 - 2012 ', ' 2011 - 2012'), ('2012 - 2013 ', ' 2012 - 2013'), ('2013 - 2014 ', ' 2013 - 2014'), ('2014 - 2015 ', ' 2014 - 2015'), ('2015 - 2016 ', ' 2015 - 2016'), ('2016 - 2017 ', ' 2016 - 2017'), ('2017 - 2018 ', ' 2017 - 2018'), ('2018 - 2019 ', ' 2018 - 2019')], max_length=13, verbose_name='Eğitim Yılı')),
                ('egit_donem', models.CharField(choices=[('GÜZ', 'GÜZ'), ('BAHAR', 'BAHAR')], max_length=10, verbose_name='Dönem')),
                ('akademisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudek.Akademisyen')),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudek.Bolum')),
                ('cikti', models.ManyToManyField(to='mudek.Cikti')),
            ],
            options={
                'verbose_name': 'Dersler',
                'verbose_name_plural': 'Dersler',
            },
        ),
        migrations.CreateModel(
            name='Fakulte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakulte_adi', models.CharField(choices=[('Orman Fakültesi', 'Orman Fakültesi'), ('Mühendislik Fakültesi', 'Mühendislik Fakültesi')], default='Mühendislik Fakültesi', max_length=25, verbose_name='Fakülte Adı')),
            ],
            options={
                'verbose_name': 'Fakülteler',
                'verbose_name_plural': 'Fakülteler',
            },
        ),
        migrations.CreateModel(
            name='Notlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('al_not', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Alınan Not')),
            ],
            options={
                'verbose_name': 'Notlar',
                'verbose_name_plural': 'Notlar',
            },
        ),
        migrations.CreateModel(
            name='Ogr_Cikti_Bas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogr_cikti_bas', models.FloatField(verbose_name='Öğrenci Çıktı Başarı Oranı')),
                ('cikti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudek.Cikti')),
            ],
            options={
                'verbose_name': 'Öğrenci Çıktı Başarı Oranı',
                'verbose_name_plural': 'Öğrenci Çıktı Başarı Oranı',
            },
        ),
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogr_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Öğrenci No')),
                ('ogr_ad', models.CharField(max_length=35, verbose_name='Öğrenci Ad')),
                ('ogr_soyad', models.CharField(max_length=25, verbose_name='Öğrenci Soyad')),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudek.Bolum')),
            ],
            options={
                'verbose_name': 'Öğrenciler',
                'verbose_name_plural': 'Öğrenciler',
            },
        ),
        migrations.CreateModel(
            name='Sinav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinav_tur', models.CharField(choices=[('Ara Sınav', 'Ara Sınav'), ('Final', 'Final'), ('Uygulama', 'Uygulama'), ('Bütünleme', 'Bütünleme'), ('Mezuniyet', 'Mezuniyet')], max_length=25, verbose_name='Sınav Türü')),
                ('sinav_tarih', models.DateField(verbose_name='Sınav Tarihi')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudek.Ders')),
            ],
            options={
                'verbose_name': 'Sınavlar',
                'verbose_name_plural': 'Sınavlar',
            },
        ),
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_no', models.PositiveIntegerField(verbose_name='Soru Numarası')),
                ('soru_puan', models.PositiveIntegerField(verbose_name='Soru Puanı')),
                ('cikti', models.ManyToManyField(to='mudek.Cikti')),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudek.Sinav')),
            ],
            options={
                'verbose_name': 'Sorular',
                'verbose_name_plural': 'Sorular',
            },
        ),
        migrations.CreateModel(
            name='Soru_Cikti_Oran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oran', models.FloatField(verbose_name='Soru Çıktı Oranı')),
                ('cikti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudek.Cikti')),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudek.Soru')),
            ],
            options={
                'verbose_name': 'Soru Çıktı Oranları',
                'verbose_name_plural': 'Soru Çıktı Oranları',
            },
        ),
        migrations.AddField(
            model_name='ogr_cikti_bas',
            name='ogrenci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudek.Ogrenci'),
        ),
        migrations.AddField(
            model_name='notlar',
            name='ogrenci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudek.Ogrenci'),
        ),
        migrations.AddField(
            model_name='notlar',
            name='soru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudek.Soru'),
        ),
        migrations.AddField(
            model_name='ders',
            name='ogrenci',
            field=models.ManyToManyField(to='mudek.Ogrenci'),
        ),
        migrations.AddField(
            model_name='bolum',
            name='fakulte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudek.Fakulte'),
        ),
        migrations.AddField(
            model_name='akademisyen',
            name='bolum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudek.Bolum'),
        ),
    ]
